In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("full_moviedata.csv")
df.head()

,Unnamed: 0,Actors,Awards,BoxOffice,Country,DVD,Director,Episode,Error,Genre,...,Type,Unnamed: 0.1,Website,Writer,Year,imdbID,imdbRating,imdbVotes,seriesID,totalSeasons
0,0,"Charlize Theron, Christina Ricci, Bruce Dern, ...",Won 1 Oscar. Another 29 wins & 25 nominations.,"$34,187,787","Germany, USA",01 Jun 2004,Patty Jenkins,NaN,NaN,"Biography, Crime, Drama, Thriller",...,movie,0,http://www.monsterfilm.com/,Patty Jenkins,2003,tt0340855,7.3,"123,001",NaN,NaN
1,1,"Devon Alan, Laura Harris, Zooey Deschanel, Mar...",1 nomination.,NaN,"Canada, USA",NaN,Marcel Sarmiento,NaN,NaN,NaN,...,movie,1,NaN,Marcel Sarmiento,2003,tt0339882,6.6,31,NaN,NaN
2,2,"Halle Berry, Robert Downey Jr., Charles S. Dut...",3 wins & 7 nominations.,"$59,537,388","USA, France, Canada, Spain",23 Mar 2004,Mathieu Kassovitz,NaN,NaN,"Horror, Mystery, Thriller",...,movie,2,http://gothikamovie.warnerbros.com/,Sebastian Gutierrez,2003,tt0348836,5.8,"99,552",NaN,NaN
3,3,"Sean Connery, Naseeruddin Shah, Peta Wilson, T...",12 nominations.,"$66,327,144","USA, Germany, Czech Republic, UK",16 Dec 2003,Stephen Norrington,NaN,NaN,"Action, Adventure, Fantasy, Sci-Fi",...,movie,3,http://www.lxgmovie.com,"Alan Moore (comic books), Kevin O'Neill (comic...",2003,tt0311429,5.8,"156,033",NaN,NaN
4,4,"Pamela Anderson, Jenny McCarthy, Marny Eng, Ch...",2 wins & 4 nominations.,NaN,"USA, Canada",11 May 2004,David Zucker,NaN,NaN,Comedy,...,movie,4,http://www.scarymovie.com/sm3_home.html,"Craig Mazin, Pat Proft, Shawn Wayans (characte...",2003,tt0306047,5.5,"126,494",NaN,NaN

In [3]:
df.columns

Index(['Unnamed: 0', 'Actors', 'Awards', 'BoxOffice', 'Country', 'DVD',
       'Director', 'Episode', 'Error', 'Genre', 'Language', 'Metascore',
       'Plot', 'Poster', 'Production', 'Rated', 'Ratings', 'Released',
       'Response', 'Runtime', 'Season', 'Title', 'Type', 'Unnamed: 0.1',
       'Website', 'Writer', 'Year', 'imdbID', 'imdbRating', 'imdbVotes',
       'seriesID', 'totalSeasons'],
      dtype='object')